package com.learning.chat.dto;

import io.swagger.v3.oas.annotations.media.Schema;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Schema(description = "AI chat response payload containing generated content and token usage statistics")
public class ChatResponseDto {

    @Schema(description = "The text content generated by the AI model", example = "Spring AI is a framework for developing AI-powered applications in Spring Boot.")
    private String content;

    @Schema(description = "Number of tokens in the prompt", example = "42")
    private Integer promptTokens;

    @Schema(description = "Number of tokens in the generated response", example = "128")
    private Integer completionTokens;

    @Schema(description = "Total tokens consumed (prompt + completion)", example = "170")
    private Integer totalTokens;
}
